
--CREATE TABLE TASK
CREATE TABLE tasks(
    Id INTEGER PRIMARY KEY AUTO_INCREMENT = 1,
    Title VARCHAR(200) NOT NULL,
    Description VARCHAR(300),
    Done BOOLEAN NOT NULL DEFAULT 0,
    CreateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);